# -*- coding: utf-8 -*-
"""Question_two.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSYcE46wtaGtN0TZtSpA99o5COQUjpsT
"""

import csv

def find_minimum_price(file_path, food_items):
    restaurant_data = {}
    with open(file_path, 'r') as file:
        csv_reader = csv.DictReader(file)
        for row in csv_reader:
            restaurant_id = int(row['restaurant_id'])
            food_item_name = row['food_item_name']
            price = float(row['price'])


            if restaurant_id not in restaurant_data:
                restaurant_data[restaurant_id] = {}

            restaurant_data[restaurant_id][food_item_name] = price

    restaurant_prices = {}
    for restaurant_id, items in restaurant_data.items():
        if all(item in items for item in food_items):
            total_price = sum(items[item] for item in food_items)
            restaurant_prices[restaurant_id] = total_price


    if not restaurant_prices:
        return "No matching restaurant found"


    min_restaurant = min(restaurant_prices, key=restaurant_prices.get)
    return min_restaurant, restaurant_prices[min_restaurant]

file_path = '/question_two_data.csv'
input_items_1 = ['burger', 'tofu_log']
input_items_2 = ['chef_salad', 'wine_spritzer']
result_1 = find_minimum_price(file_path, input_items_1)
print("Output-1:", result_1)
result_2 = find_minimum_price(file_path, input_items_2)
print("Output-2:", result_2)

