# -*- coding: utf-8 -*-
"""Questionone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R4RtFRqVypDIxD3yhuB4D9kLkEEUcgyy
"""

def get_directory_size(file_system, path):
    dirs = path.split(".")
    current = file_system
    for directory in dirs:
        if directory in current:
            current = current[directory]
        else:
            return f"Directory '{path}' not found."

    def calculate_size(directory):
        total_size = 0
        for key, value in directory.items():
            if isinstance(value, dict):
                total_size += calculate_size(value)
            elif isinstance(value, int):
                total_size += value
        return total_size

    total_size = calculate_size(current)

    return f"Total size: {total_size}"


file_system = {
    "root": {
        "dir1": {
            "subdir1": {
                "file1.txt": 500,
                "file2.txt": 500
            },
            "subdir2": {
                "file3.txt": 800
            }
        },
        "dir2": {
            "subdir3": {
                "file4.txt": 2000
            },
            "subdir4": {
                "subsubdir5": {
                    "file5.txt": 1200,
                    "file6.txt": 2200
                }
            }
        }
    }
}

print(get_directory_size(file_system, "root.dir1.subdir1"))
print(get_directory_size(file_system, "root.dir2.subdir4.subsubdir5"))
print(get_directory_size(file_system, "root.dir3"))
print(get_directory_size(file_system, "root.dir2.subdir4.subsubdir5.file6.txt"))

